services:
  - type: web
    name: resume-builder-server
    runtime: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: node server/index.js
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: resume-builder-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://resumebuilder-opal-five.vercel.app

databases:
  - name: resume-builder-db
    databaseName: resume-builder
    plan: free
